
/* Script DDL de création pour les contraintes de champs */
/* .................................................................................... */

ALTER TABLE T_HOUSEHOLD_HSH ALTER COLUMN HSH_VISIT_RESULT SET DEFAULT '99'^

ALTER TABLE T_HOUSEHOLD_HSH ALTER COLUMN HSH_VISIT_DAY SET RANGE 1 31^
ALTER TABLE T_HOUSEHOLD_HSH ALTER COLUMN HSH_VISIT_MONTH SET RANGE 1 12^
ALTER TABLE T_HOUSEHOLD_HSH ALTER COLUMN HSH_VISIT_YEAR SET RANGE 1920 2012^

ALTER TABLE T_HOUSEHOLD_HSH ALTER COLUMN HSH_VISIT_RESULT CHECK '1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7 OR 8 OR 9 OR 10 OR 97 OR 99'^

